In [21]:
from utils import data_dir
import pandas as pd
from collections import defaultdict

In [6]:
main = next(data_dir().rglob('analysis'))

In [31]:
store = defaultdict(list)
for folder in list(main.iterdir()):
    if 'DS' in folder.name:
        continue
    store['id'].append(folder.name)
    for file in folder.iterdir():
        df = pd.read_csv(file)
        val_sum = int(df.value.sum())
        if 'energy' in file.name:
            store['energy'].append(val_sum)
        if 'gas' in file.name:
            store['gas'].append(val_sum)
data = pd.DataFrame(store)

In [35]:
len(data[ data.energy > 25]) / len(data)

0.43373493975903615

In [37]:
data

          id    energy      gas
0   10231992        23       23
1   10250992   4785355  1563925
2   10279992        23       23
3     104991        23       23
4   10858992    540334    25732
5     110991        24       24
6   11581992        23       23
7   11586992        23       23
8   11606992        23       23
9   11851992        24       24
10    121991        23       23
11    121993        23       23
12    124991        23       23
13    124993        23       23
14    125991   1479455   238061
15    125993   1521571   240112
16    125994     75397    11208
17    125995     91037    11418
18  13202992   5139338  1259953
19  13206992  17214829  4941313
20  13255992        23       23
21   1498993        23       23
22   1534993   3736316   575427
23   1574993   2889751   417932
24   1580993   2676784   360099
25   1586993        23       23
26  15948991  11360256  3315611
27  15979991  12421755  3698124
28  15983991        23       23
29   1609993   4319978   661630
..       ...       ...      ...
53     51991        24       24
54     53991        24       24
55     59991     48724     1597
56    657993        24       24
57    661993        23       23
58    665993   9314948  1477202
59    668993        23       23
60    668994        23       23
61    671993        24       24
62    675993   2051070   282519
63   7297992        23       23
64     72991        24       24
65   7319992   8640580  2606736
66   7336992        23       23
67     75991        24       24
68     76991        24       24
69     77991        24       24
70     78991   1261314   172067
71     79991        23       23
72   8117992   3267812   847120
73     82991        23       23
74   8340992    518019    15902
75     84991        24       24
76   8547992    560377    19660
77     85991        24       24
78     87991        24       24
79   9307992        23       23
80   9325992        23       23
81   9923992  12819428  3560498
82    998993   1802573   237953

[83 rows x 3 columns]